/*
 * This source file was generated by the Gradle 'init' task
 */
package com.oz;

import javax.sql.DataSource;
import com.oz.config.Config;
import com.oz.db.DatabaseFactory;
import com.oz.db.MigrationRunner;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import com.oz.ui.MainController;

public class App extends Application {
	public static void main(String[] args) {
		Config.load();
		DataSource ds = DatabaseFactory.getDataSource();
		MigrationRunner.initDatabase(ds);
		FXMLLoader loader = new FXMLLoader(App.class.getResource("/views/index.fxml"));
		loader.setControllerFactory(clazz -> {
			if (clazz == MainController.class) {
				return new MainController();
			}
			return null;
		});

		Parent root = loader.load();
	}
}
